name: libry
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  page_transition: ^2.2.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  stylish_bottom_bar:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/icons/
   - assets/images/

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster_Two/LobsterTwo-Bold.ttf
          weight: 800
        - asset: assets/fonts/Lobster_Two/LobsterTwo-Regular.ttf
          weight: 500

    - family: Livvic
      fonts:
        - asset: assets/fonts/Livvic/Livvic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Livvic/Livvic-Regular.ttf
          weight: 600
        - asset: assets/fonts/Livvic/Livvic-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Livvic/Livvic-Bold.ttf
          weight: 800